### ISSUE TITLE
running on windows

### ISSUE THREAD

**Issue by yusuf8834** [Khunanon-Chanasongkhram/DisVar#1]
Hi,

Thank you for this amazing library. I'm encountering an issue when I try to run the library on Windows 11. The error message I see in my console seems to be related to this issue is: _"'grep' is not recognized as an internal or external command, operable program or batch file."_ I don't have this problem when I use Linux.

Thanks for your help.

```
> library(DisVar)
> DisVar("./downloads/SL470811.hard-filtered.vcf")
Loading required package: sqldf
Loading required package: gsubfn
Loading required package: proto
Loading required package: RSQLite
Loading required package: data.table
data.table 1.14.8 using 8 threads (see ?getDTthreads).  Latest news: r-datatable.com
Loading required package: dplyr

Attaching package: ‘dplyr’

The following objects are masked from ‘package:data.table’:

    between, first, last

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Reading files...
'grep' is not recognized as an internal or external command,
operable program or batch file.
Reading files...DONE
Searching...
Searching...DONE
Processing results...
Error in DisVar("./downloads/SL470811.hard-filtered.vcf") : 
  No variant was found in the database
```

**Comment by Khunanon-Chanasongkhram** [comment]
Hi,

Thank you for reporting the issue. I’m glad to inform you that the issue has been resolved. The DisVar package is now compatible with Windows, without encountering the “grep” error. If you experience any further issues, feel free to reach out. We apologize for any inconvenience caused by the initial problem.

Best regards,
KC
